## 디버그 여부 - 로깅이 디버그 모드로 실행됨
debug: false

## 액츄에이터 엔드포인트를 모두 노출 (보안 주의)
management:
  endpoints:
    web:
      exposure:
        include: "*"

## 로깅 레벨 설정
logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA 쿼리 로그 디버깅

## Spring 설정
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: jsun
    password: 1234

  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true # Test DB 생성 가능, resources 내 data.sql 로 초기화
    hibernate.ddl-auto: create # create로 설정 시 데이터베이스를 재생성할 수 있음 (none 추천)
    show-sql: true # 실행되는 SQL 문을 로그로 출력
    properties:
      hibernate.format_sql: true # 포맷된 SQL 로그 출력
      hibernate.default_batch_fetch_size: 100 # 벌크 데이터 가져오기 최적화
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3.decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: {baseUrl}/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always
